### PR TITLE
Changes during MEEG Review

### PR DESCRIPTION
**Pull request by pravsripad**
1. Remove prefix line for conda environments (the env should be created in the default location for the user).
2. Add name mne_meg01 to meeg environment file.
3. Removed old meeg_environment.txt file
4. Fix `from config import bids_root` imports.
5. Update requirements to provide exact builds and also provide one with generic package lists.

### CODE REVIEW

**Comment by pravsripad** [comment]
Fixes #9

**Comment by pravsripad** [comment]
Hi @oscfer88 @yilingsp , I've started reviewing and making some minor changes to the code. They are listed above. Please have a look.

**Comment by oscfer88** [comment]
Hi @pravsripad, I had a loo at he commits and everything looks fine to me

**Review by oscfer88 — APPROVED** [review]
All good

**Pull request merged**
