### PR TITLE
Upload MEG scripts

### PR DESCRIPTION
**Pull request by oscfer88**
this includes:
- preprocessing
- source modelling
- GED
- connectivity
- activation

### CODE REVIEW

**Comment by pravsripad** [comment]
@oscfer88 quick question does this PR include both yours and @yilingsp Ling's code?

**Comment by yilingsp** [comment]
no, I am still try to figure out how to put my code on this repository, If all my code already on an folder called ROI_MVPA, how should I do to uploading my code to the correct location?

Best
Ling


***@***.***
 
From: Praveen Sripad
Date: 2023-06-16 18:16
To: Cogitate-consortium/cogitate-msp1
CC: Ling Liu (PKU); Mention
Subject: Re: [Cogitate-consortium/cogitate-msp1] Upload MEG scripts (PR #14)
@oscfer88 quick question does this PR include both yours and @yilingsp Ling's code?

**Review by pravsripad — APPROVED** [review]
The `about.md` and environment files are missing. This can be added as part of the full review #9 . Thanks for uploading the code @oscfer88 .

**Comment by pravsripad** [comment]
@nbonacchi changes were approved but I still see that Merging into main is blocked, what are we missing?

**Comment by nbonacchi** [comment]
done!

**Pull request merged**
